# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ff873ee9d154dddf71fbc569a09232e8be6aced0bc63595b9a9f4fd1aaa2b21bdc8149f48be63e064983e77c438dfea29dcc8ad9bab75cf86b348be005ec45

test:
  secret_key_base: 9d08bd409608c47b1c9dbf9dac98e1f2716328ca03e28b58db93a1cb426a6333dafe678505101b3a506f2761f94061e624682685cb695a1d398df3e5ef047e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
